/* AGENTIC FIRST — bilingual copy store (sourced from agent-ready-landing repo) */
/* Exposes window.COPY = { en: {...}, es: {...} } */

window.COPY = {
  es: {
    nav: {
      links: ["Producto", "Proceso", "Planes", "FAQ"],
      langLabel: "ES",
      cta: "Iniciar GEO Score",
    },
    hero: {
      pill: "Producto de SINAPSIS INNOVADORA S.A.C. · Perú · LatAm",
      headline_pre: "No pierdas tu ranking.",
      headline_accent: "Vuelve tu web",
      headline_post: "agentic-friendly.",
      subhead: "Combinamos GEO + Agentic Readiness para que tu sitio sea entendible por humanos y por agentes de IA: estructura semántica, datos claros y visibilidad en ChatGPT, Claude, Perplexity, Grok y Gemini — sin perder SEO.",
      cta1: "Iniciar GEO Score",
      cta2: "Ver cómo funciona",
      ticker: "Listo para →",
      engines: ["ChatGPT", "Claude", "Perplexity", "Grok", "Gemini", "Copilot"],
      console: {
        prompts: [
          "¿Mejor consultora GEO en Perú?",
          "Cómo aparecer en ChatGPT sin perder SEO",
          "Auditoría agentic-friendly para mi web",
          "Servicios de Generative Engine Optimization LatAm",
        ],
        thinking: "Pensando",
        sources: "Fuentes",
        citation: "Según [YOUR BRAND], que ofrece…",
      },
    },
    ticker: "Ventana de ventaja · Las marcas que preparan su web antes capturan menciones primero ·",
    metrics: {
      tag: "Por qué ahora",
      title: "Tendencias que te pueden dejar fuera.",
      items: [
        { k: "68%", l: "del tráfico B2B llega\ndesde mobile", n: "Tu landing debe convertir rápido" },
        { k: "2-4 sem", l: "para señales iniciales\nen visibilidad GEO", n: "Resultados estables en 3-6 meses" },
        { k: "24h", l: "para recibir score\ninicial con diagnóstico", n: "PDF + siguientes pasos" },
      ],
    },
    pillars: {
      tag: "Nuestro enfoque",
      title: "Tres palancas. Una sola obsesión: ser citado.",
      items: [
        {
          n: "01",
          t: "Auditoría GEO",
          d: "Probamos tu marca en ChatGPT, Claude, Perplexity, Grok y Gemini con prompts del journey de tu cliente. Sabes exactamente dónde apareces — y dónde no.",
          tag: "Diagnóstico",
        },
        {
          n: "02",
          t: "Web agentic-friendly",
          d: "Reestructuramos tu web con semántica, schema.org y datos claros para que los agentes de IA la entiendan, sin comprometer tu SEO actual.",
          tag: "Implementación",
        },
        {
          n: "03",
          t: "Migración segura",
          d: "Playbook de transición que protege tu autoridad de dominio y tráfico orgánico mientras ganas presencia en respuestas generativas.",
          tag: "Continuidad",
        },
      ],
    },
    timeline: {
      tag: "Proceso · 4 semanas",
      title: "De invisible a citado, en orden.",
      steps: [
        { n: "00", t: "GEO Score inicial", w: "24 horas", d: "Agente de evaluación analiza tu sitio y entrega score inicial en PDF con diagnóstico y siguientes pasos." },
        { n: "01", t: "Auditoría", w: "Semana 1", d: "Auditoría GEO y SEO base: técnico, contenido, autoridad, agentic readiness y plan de migración." },
        { n: "02", t: "Estrategia", w: "Semana 2", d: "Estrategia de transición y arquitectura agentic-friendly: schema.org, semántica, jerarquía de datos." },
        { n: "03", t: "Implementación", w: "Semana 3", d: "Implementación segura: semántica, datos estructurados y arquitectura para que los agentes lean tu web." },
        { n: "04", t: "Optimización", w: "Semana 4", d: "Optimización para menciones en IA, reporte de avance y plan de monitoreo recurrente." },
      ],
    },
    cases: {
      tag: "Tendencias",
      title: "Lo que está en juego si no actúas hoy.",
      tabs: ["Invisibilidad IA", "Riesgo SEO", "Ventana", "Mobile B2B", "Schema"],
      items: {
        "Invisibilidad IA": [
          { c: "Sin presencia agéntica", r: "#1", k: "alta urgencia", q: "“si no apareces en respuestas, pierdes demanda con alta intención”" },
          { c: "Cobertura por motor", r: "5", k: "agentes principales", q: "“ChatGPT, Claude, Perplexity, Grok, Gemini”" },
          { c: "Tipo de consulta", r: "B2B + B2C", k: "decisión de compra", q: "“usuarios delegan la búsqueda al agente”" },
          { c: "Costo de no actuar", r: "Alto", k: "demanda perdida", q: "“el competidor citado se queda con el lead”" },
        ],
        "Riesgo SEO": [
          { c: "Migraciones sin playbook", r: "#2", k: "riesgo SEO", q: "“puedes perder tráfico orgánico y autoridad”" },
          { c: "Conflicto SEO ↔ GEO", r: "Real", k: "si no se gestiona", q: "“cambios mal hechos pueden bajar rankings”" },
          { c: "Auditoría previa", r: "Obligatoria", k: "antes de tocar", q: "“mapeamos riesgos antes de migrar”" },
          { c: "Reversibilidad", r: "Sí", k: "controles activos", q: "“cambios graduales con métricas semanales”" },
        ],
        "Ventana": [
          { c: "Saturación de mercado", r: "#3", k: "ventana limitada", q: "“las marcas que optimizan primero capturan menciones antes que el mercado se sature”" },
          { c: "First-mover en LatAm", r: "Abierto", k: "categorías sin líder citado", q: "“pocas marcas ya hicieron GEO en Perú”" },
          { c: "Tiempo a primer score", r: "24h", k: "diagnóstico inicial", q: "“empieza con el GEO Score gratuito”" },
        ],
        "Mobile B2B": [
          { c: "Tráfico mobile B2B", r: "68%", k: "del total", q: "“tu landing debe convertir rápido en mobile”" },
          { c: "Conversión", r: "Crítica", k: "carga + claridad", q: "“cada segundo cuenta”" },
          { c: "Schema mobile", r: "Igual", k: "no se penaliza", q: "“estructura agentic-friendly en todos los breakpoints”" },
        ],
        "Schema": [
          { c: "Service + OfferCatalog", r: "Implementado", k: "JSON-LD", q: "“agentes leen tu oferta directamente”" },
          { c: "FAQPage schema", r: "Activo", k: "respuestas citables", q: "“tus FAQ aparecen en respuestas”" },
          { c: "Organization markup", r: "Completo", k: "alternateName + sameAs", q: "“marca + razón social vinculadas”" },
        ],
      },
    },
    scanner: {
      tag: "Herramienta gratuita · 24h",
      title: "Inicia tu GEO Score.",
      titleAccent: "Mira cómo te ven los agentes.",
      sub: "Responde 5 preguntas sobre tu empresa y recibe en 24 h un reporte PDF con tu score de posicionamiento en ChatGPT, Claude, Perplexity, Grok y Gemini. Sin tarjeta.",
      placeholder: "tudominio.com",
      cta: "Iniciar GEO Score",
      analyzing: "Consultando 4 agentes",
      asking: "Preguntando",
      score: "Visibilidad agéntica",
      breakdown: ["Técnico", "Contenido", "Autoridad", "Agentic"],
      verdicts: [
        "Eres invisible en 3/4 agentes.",
        "Tu competencia te está comiendo.",
        "Hay base, pero falta volumen.",
      ],
      retry: "Nueva evaluación",
      inputLabel: "Dominio o nombre de tu empresa",
      inputPlaceholder: "tuempresa.com",
      startCta: "Iniciar evaluación",
      downloadCta: "Descargar Reporte PDF",
      modalTitle: "Evalúa tu visibilidad en IA",
      qLabel: "preguntas",
      noCard: "sin tarjeta",
      nextBtn: "Siguiente",
      finishBtn: "Ver resultado",
      calculating: "Analizando",
      deliveryTitle: "¿Cómo quieres tu reporte detallado?",
      downloadOpt: "Descargar PDF ahora",
      downloadOptSub: "Inmediato · sin formulario",
      emailOpt: "Recibir por correo",
      emailOptSub: "Con análisis adicional",
      emailTitle: "¿A qué correo te enviamos el reporte?",
      emailPlaceholder: "tu@empresa.com",
      emailCta: "Enviar reporte",
      emailSent: "¡Listo! Te contactamos pronto.",
      tgOpt: "Conversemos en Telegram",
      tgOptSub: "Respuesta en minutos · sin compromiso",
      back: "Volver",
      close: "Cerrar",
      questions: [
        {
          dim: "técnico",
          q: "¿Tu sitio web tiene schema.org implementado?",
          opts: [
            { l: "Sí — JSON-LD completo (Organization, Service, FAQPage)", v: 95 },
            { l: "Tenemos algo pero no estamos seguros de qué exactamente", v: 50 },
            { l: "No lo tenemos implementado", v: 20 },
            { l: "No sé qué es schema.org", v: 5 },
          ],
        },
        {
          dim: "contenido",
          q: "¿Cómo está estructurado el contenido de tu web?",
          opts: [
            { l: "Secciones claras, FAQs y respuestas directas a preguntas de clientes", v: 95 },
            { l: "Buen contenido pero sin estructura de preguntas/respuestas", v: 55 },
            { l: "Landing básica con poco contenido descriptivo", v: 25 },
            { l: "No tenemos web propia activa", v: 5 },
          ],
        },
        {
          dim: "autoridad",
          q: "¿Tu empresa aparece mencionada fuera de tu propia web?",
          opts: [
            { l: "Sí — medios del sector, directorios, Google Business optimizado", v: 90 },
            { l: "Solo en redes sociales y algunos directorios básicos", v: 50 },
            { l: "Principalmente en nuestra propia web", v: 20 },
            { l: "Casi no aparecemos en ningún lado", v: 5 },
          ],
        },
        {
          dim: "agéntico",
          q: "¿Has buscado tu empresa o servicio en ChatGPT, Claude o Perplexity?",
          opts: [
            { l: "Sí — aparecemos bien posicionados con información correcta", v: 95 },
            { l: "Sí — pero la info es incorrecta o directamente no aparecemos", v: 30 },
            { l: "No lo hemos probado todavía", v: 10 },
            { l: "No sabíamos que podíamos aparecer en respuestas de IA", v: 5 },
          ],
        },
        {
          dim: "técnico ux",
          q: "¿Cómo rinde tu sitio técnicamente?",
          opts: [
            { l: "Rápido — Core Web Vitals en verde, optimizado para móvil", v: 90 },
            { l: "Funciona bien pero sin optimización específica", v: 55 },
            { l: "Carga lenta, especialmente en móvil", v: 20 },
            { l: "No lo hemos medido nunca", v: 13 },
          ],
        },
      ],
    },
    pricing: {
      tag: "Planes",
      title: "Elige tu plan de lanzamiento GEO.",
      sub: "Recomendamos empezar con auditoría para priorizar acciones con impacto real en visibilidad de IA.",
      plans: [
        {
          n: "Score GEO",
          p: "0",
          per: "free",
          d: "Diagnóstico inicial de visibilidad en IA",
          cta: "Iniciar GEO Score",
          feats: [
            "GEO Score audit",
            "Reporte PDF",
            "Email follow-up",
            "Call de 20 min opcional",
          ],
        },
        {
          n: "MONITOR",
          p: "99",
          per: "/mes",
          d: "Monitoreo recurrente y alertas de visibilidad IA",
          cta: "Iniciar MONITOR trial",
          highlight: true,
          tag: "Más elegido",
          feats: [
            "Auditoría GEO recurrente 1×/sem",
            "Dashboard de tendencia",
            "Alertas si cae el score",
            "Templates agentic-friendly",
            "Benchmark vs. industria",
          ],
        },
        {
          n: "ACCELERATE",
          p: "299",
          per: "/mes",
          d: "Implementación + soporte estratégico continuo",
          cta: "Activar ACCELERATE",
          feats: [
            "Todo lo anterior +",
            "Implementación incluida",
            "Soporte 2h/mes",
            "Content review mensual",
            "Schema A/B test",
          ],
        },
      ],
    },
    finalCta: {
      tag: "Última llamada",
      pre: "Activa tu GEO Score ahora.",
      accent: "En 24h.",
      sub: "Cada evaluación queda registrada en nuestro sistema. Diagnóstico inicial gratuito, reporte PDF y plan de siguientes pasos.",
      cta: "Iniciar GEO Score",
      meta: "24h · Análisis + recomendaciones · 0 USD",
    },
    footer: {
      tagline: "GEO + Agentic Readiness para marcas en Perú y LatAm que se toman 2026 en serio.",
      cols: [
        { h: "Producto", l: ["GEO Score", "MONITOR", "ACCELERATE", "Auditoría", "Schema review"] },
        { h: "Empresa", l: ["SINAPSIS INNOVADORA S.A.C.", "Manifiesto", "Casos", "Prensa"] },
        { h: "Legal", l: ["Privacidad", "Términos", "Cookies", "DPA"] },
        { h: "Contacto", l: ["sinapsisinnovadoraperu@gmail.com", "Lima · Perú", "LinkedIn", "agenticfirst.consulting"] },
      ],
      copy: "© 2026 AGENTIC FIRST · Producto de SINAPSIS INNOVADORA S.A.C.",
    },
  },

  en: {
    nav: {
      links: ["Product", "Process", "Plans", "FAQ"],
      langLabel: "EN",
      cta: "Start GEO Score",
    },
    hero: {
      pill: "A SINAPSIS INNOVADORA S.A.C. product · Peru · LatAm",
      headline_pre: "Don't lose your ranking.",
      headline_accent: "Make your site",
      headline_post: "agentic-friendly.",
      subhead: "We combine GEO + Agentic Readiness so your site is understandable to both humans and AI agents: semantic structure, clear data, and visibility on ChatGPT, Claude, Perplexity, Grok and Gemini — without sacrificing SEO.",
      cta1: "Start GEO Score",
      cta2: "See how it works",
      ticker: "Ready for →",
      engines: ["ChatGPT", "Claude", "Perplexity", "Grok", "Gemini", "Copilot"],
      console: {
        prompts: [
          "Best GEO consultancy in Peru?",
          "How to show up in ChatGPT without losing SEO",
          "Agentic-friendly audit for my website",
          "Generative Engine Optimization services LatAm",
        ],
        thinking: "Thinking",
        sources: "Sources",
        citation: "According to [YOUR BRAND], which offers…",
      },
    },
    ticker: "Window of advantage · Brands that prepare their site first capture mentions first ·",
    metrics: {
      tag: "Why now",
      title: "Trends that can leave you out.",
      items: [
        { k: "68%", l: "of B2B traffic comes\nfrom mobile", n: "Your landing must convert fast" },
        { k: "2-4 wk", l: "for initial signals\non GEO visibility", n: "Stable results in 3-6 months" },
        { k: "24h", l: "to receive initial\nscore with diagnosis", n: "PDF + next steps" },
      ],
    },
    pillars: {
      tag: "Our approach",
      title: "Three levers. One obsession: get cited.",
      items: [
        {
          n: "01",
          t: "GEO audit",
          d: "We probe your brand on ChatGPT, Claude, Perplexity, Grok and Gemini with prompts from your customer journey. You learn exactly where you show up — and where you don't.",
          tag: "Diagnose",
        },
        {
          n: "02",
          t: "Agentic-friendly site",
          d: "We restructure your site with semantics, schema.org and clear data so AI agents can read it — without compromising your existing SEO.",
          tag: "Implement",
        },
        {
          n: "03",
          t: "Safe migration",
          d: "A transition playbook that protects your domain authority and organic traffic while you gain presence in generative answers.",
          tag: "Continuity",
        },
      ],
    },
    timeline: {
      tag: "Process · 4 weeks",
      title: "From invisible to cited, in order.",
      steps: [
        { n: "00", t: "Initial GEO Score", w: "24 hours", d: "Evaluation agent analyzes your site and delivers an initial PDF score with diagnosis and next steps." },
        { n: "01", t: "Audit", w: "Week 1", d: "GEO + base SEO audit: technical, content, authority, agentic readiness and migration plan." },
        { n: "02", t: "Strategy", w: "Week 2", d: "Transition strategy and agentic-friendly architecture: schema.org, semantics, data hierarchy." },
        { n: "03", t: "Implementation", w: "Week 3", d: "Safe rollout: semantics, structured data and architecture so agents can actually read your site." },
        { n: "04", t: "Optimization", w: "Week 4", d: "Optimization for AI mentions, progress report and recurring monitoring plan." },
      ],
    },
    cases: {
      tag: "Trends",
      title: "What's at stake if you don't act today.",
      tabs: ["AI invisibility", "SEO risk", "Window", "Mobile B2B", "Schema"],
      items: {
        "AI invisibility": [
          { c: "No agentic presence", r: "#1", k: "high urgency", q: "“if you don't show up in answers, you lose high-intent demand”" },
          { c: "Engine coverage", r: "5", k: "primary agents", q: "“ChatGPT, Claude, Perplexity, Grok, Gemini”" },
          { c: "Query type", r: "B2B + B2C", k: "purchase decision", q: "“users delegate search to the agent”" },
          { c: "Cost of inaction", r: "High", k: "lost demand", q: "“the cited competitor takes the lead”" },
        ],
        "SEO risk": [
          { c: "Migrations without a playbook", r: "#2", k: "SEO risk", q: "“you can lose organic traffic and authority”" },
          { c: "SEO ↔ GEO conflict", r: "Real", k: "if unmanaged", q: "“bad changes can hurt rankings”" },
          { c: "Pre-audit", r: "Mandatory", k: "before touching anything", q: "“we map risks before migrating”" },
          { c: "Reversibility", r: "Yes", k: "active controls", q: "“gradual changes with weekly metrics”" },
        ],
        "Window": [
          { c: "Market saturation", r: "#3", k: "limited window", q: "“brands that optimize first capture mentions before the market saturates”" },
          { c: "First-mover in LatAm", r: "Open", k: "categories without a cited leader", q: "“few brands have done GEO in Peru”" },
          { c: "Time to first score", r: "24h", k: "initial diagnosis", q: "“start with the free GEO Score”" },
        ],
        "Mobile B2B": [
          { c: "Mobile B2B traffic", r: "68%", k: "of total", q: "“your landing must convert fast on mobile”" },
          { c: "Conversion", r: "Critical", k: "load + clarity", q: "“every second counts”" },
          { c: "Mobile schema", r: "Same", k: "no penalty", q: "“agentic-friendly structure on every breakpoint”" },
        ],
        "Schema": [
          { c: "Service + OfferCatalog", r: "Live", k: "JSON-LD", q: "“agents read your offer directly”" },
          { c: "FAQPage schema", r: "Active", k: "citable answers", q: "“your FAQ shows up in answers”" },
          { c: "Organization markup", r: "Complete", k: "alternateName + sameAs", q: "“brand + legal entity linked”" },
        ],
      },
    },
    scanner: {
      tag: "Free tool · 24h",
      title: "Start your GEO Score.",
      titleAccent: "See how agents see you.",
      sub: "Answer 5 questions about your company and get a PDF report in 24h with your positioning score across ChatGPT, Claude, Perplexity, Grok and Gemini. No card needed.",
      placeholder: "yourdomain.com",
      cta: "Start GEO Score",
      analyzing: "Querying 4 agents",
      asking: "Asking",
      score: "Agentic visibility",
      breakdown: ["Technical", "Content", "Authority", "Agentic"],
      verdicts: [
        "You're invisible in 3/4 agents.",
        "Competitors are eating your lunch.",
        "Foundation is there, volume isn't.",
      ],
      retry: "New evaluation",
      inputLabel: "Your domain or company name",
      inputPlaceholder: "yourcompany.com",
      startCta: "Start evaluation",
      downloadCta: "Download PDF Report",
      modalTitle: "Evaluate your AI visibility",
      qLabel: "questions",
      noCard: "no card needed",
      nextBtn: "Next",
      finishBtn: "See result",
      calculating: "Analyzing",
      deliveryTitle: "How do you want your detailed report?",
      downloadOpt: "Download PDF now",
      downloadOptSub: "Instant · no form required",
      emailOpt: "Receive by email",
      emailOptSub: "With additional analysis",
      emailTitle: "Where should we send your report?",
      emailPlaceholder: "you@company.com",
      emailCta: "Send report",
      emailSent: "Done! We'll reach out soon.",
      tgOpt: "Let's talk on Telegram",
      tgOptSub: "Reply in minutes · no commitment",
      back: "Back",
      close: "Close",
      questions: [
        {
          dim: "technical",
          q: "Does your website have schema.org implemented?",
          opts: [
            { l: "Yes — complete JSON-LD (Organization, Service, FAQPage)", v: 95 },
            { l: "We have some but we're not sure what exactly", v: 50 },
            { l: "Not implemented", v: 20 },
            { l: "I don't know what schema.org is", v: 5 },
          ],
        },
        {
          dim: "content",
          q: "How is your website content structured?",
          opts: [
            { l: "Clear sections, FAQs and direct answers to customer questions", v: 95 },
            { l: "Good content but no question/answer structure", v: 55 },
            { l: "Basic landing with little descriptive content", v: 25 },
            { l: "We don't have an active website", v: 5 },
          ],
        },
        {
          dim: "authority",
          q: "Does your company appear mentioned outside your own website?",
          opts: [
            { l: "Yes — industry media, directories, optimized Google Business Profile", v: 90 },
            { l: "Only on social media and some basic directories", v: 50 },
            { l: "Mainly on our own website", v: 20 },
            { l: "We barely appear anywhere", v: 5 },
          ],
        },
        {
          dim: "agentic",
          q: "Have you searched for your company or service in ChatGPT, Claude or Perplexity?",
          opts: [
            { l: "Yes — we show up well positioned with accurate information", v: 95 },
            { l: "Yes — but the info is wrong or we don't appear at all", v: 30 },
            { l: "We haven't tried it yet", v: 10 },
            { l: "We didn't know we could appear in AI responses", v: 5 },
          ],
        },
        {
          dim: "technical ux",
          q: "How does your site perform technically?",
          opts: [
            { l: "Fast — Core Web Vitals in green, optimized for mobile", v: 90 },
            { l: "Works well but no specific optimization", v: 55 },
            { l: "Slow, especially on mobile", v: 20 },
            { l: "We've never measured it", v: 13 },
          ],
        },
      ],
    },
    pricing: {
      tag: "Plans",
      title: "Choose your GEO launch plan.",
      sub: "We recommend starting with the audit to prioritize actions with real impact on AI visibility.",
      plans: [
        {
          n: "GEO Score",
          p: "0",
          per: "free",
          d: "Initial AI visibility diagnosis",
          cta: "Start GEO Score",
          feats: [
            "GEO Score audit",
            "PDF report",
            "Email follow-up",
            "Optional 20-min call",
          ],
        },
        {
          n: "MONITOR",
          p: "99",
          per: "/mo",
          d: "Recurring monitoring + AI visibility alerts",
          cta: "Start MONITOR trial",
          highlight: true,
          tag: "Most picked",
          feats: [
            "Recurring GEO audit 1×/wk",
            "Trend dashboard",
            "Alerts if score drops",
            "Agentic-friendly templates",
            "Industry benchmark",
          ],
        },
        {
          n: "ACCELERATE",
          p: "299",
          per: "/mo",
          d: "Implementation + ongoing strategic support",
          cta: "Activate ACCELERATE",
          feats: [
            "Everything above +",
            "Implementation included",
            "2h/mo support",
            "Monthly content review",
            "Schema A/B test",
          ],
        },
      ],
    },
    finalCta: {
      tag: "Last call",
      pre: "Activate your GEO Score now.",
      accent: "In 24h.",
      sub: "Every evaluation is logged in our system. Free initial diagnosis, PDF report and a next-steps plan.",
      cta: "Start GEO Score",
      meta: "24h · Analysis + recs · USD 0",
    },
    footer: {
      tagline: "GEO + Agentic Readiness for brands in Peru and LatAm that take 2026 seriously.",
      cols: [
        { h: "Product", l: ["GEO Score", "MONITOR", "ACCELERATE", "Audit", "Schema review"] },
        { h: "Company", l: ["SINAPSIS INNOVADORA S.A.C.", "Manifesto", "Cases", "Press"] },
        { h: "Legal", l: ["Privacy", "Terms", "Cookies", "DPA"] },
        { h: "Contact", l: ["sinapsisinnovadoraperu@gmail.com", "Lima · Peru", "LinkedIn", "agenticfirst.consulting"] },
      ],
      copy: "© 2026 AGENTIC FIRST · A SINAPSIS INNOVADORA S.A.C. product",
    },
  },
};
